package com.dyn.betterachievements.reference;

import java.util.Arrays;

import net.minecraftforge.fml.common.ModMetadata;

public class MetaData {
	public static ModMetadata init(ModMetadata metadata) {
		metadata.modId = Reference.MOD_ID;
		metadata.name = Reference.NAME;
		metadata.description = "A rewrite of the achievement screen so it makes more sense";
		metadata.url = "https://github.com/way2muchnoise/BetterAchievements";
		metadata.version = Reference.VERSION_FULL;
		metadata.authorList = Arrays.asList("way2muchnoise");
		metadata.credits = "";
		metadata.autogenerated = false;
		return metadata;
	}
}
